after_success: |
  if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then
    echo "$PGP_SECRET" | base64 --decode | gpg --import
    if [ -z "$TRAVIS_TAG" ]; then
        sbt publishSigned
    else
        sbt publishSigned sonatypeRelease
    fi
  fi
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.sbt
deploy:
  api_key:
    secure: tp8RmFVQBvS8JyJnieZ/QkB36c/0D45ZJQMGpY3c6eRTcDwOEJksEy+XhnWLB2a+6hi0pQVFs4D2m/6ZZRuNVYkfhkJgL7kqpgre1lh/zJGrYuOJc4ut3CDemOEQbpgGKEkETl+Up+nPYcTRKCttB8My7hQCbX4LmOq07QjAqhPZoYabWY3wsuFxy7Dx7lBUV30OHidllByQgSbRwiKFSqmVciWLBks98QMRQKNaCLyYHRRR/y7suHFchEJajSBQyUkGrGoaJousgu+KQmDYJwF3RE/B8A1ZZvHXS3j+uUCRiouq4hvXJiQW5e3a0Th4qSfZ39UKifRY/ihQKIGRCWJUK4xCbIDfR97MMqEqZOzhGrLsqqzcvE17LjMRX673dNEwP5EUgY02IP66FVKmAchUfRFVwrshBFGRTSuO7fbDw+Hi0AmT7Vr6IMqP3A/8TWXQrET9U/sSkcOBKNUftrIwNl2na1VHZbFeUQ0mBV5ei+ySACobb6pTcZOy5nqi19+Sq3Of6fYsj2bZYsSP8tCAGxPeOm0Nu7WInc2MqP8HbLyvHp8mNGinX0p042FvCIYD2JcGfznn9FGDb12WEga2rCwJnoq6e+5ZlMvjPNkzkiLOJv7OsC+I6TEb/P3KWzYdzOSO6JVGtHPxmXBZHhFIUUa+uqj9UbbCtA5ct/4=
  file: '*/target/**/*.jar'
  file_glob: true
  on:
    tags: true
  provider: releases
  skip_cleanup: true
git:
  depth: 1
jdk: openjdk8
language: scala
script:
  - '[ "$TRAVIS_PULL_REQUEST" != false ] || export SBT_OPTS=-Dbuild.version=${TRAVIS_TAG:-$TRAVIS_BRANCH-SNAPSHOT}'
  - sbt package
